From 61a4ac1d2aee794b34fcc9b1b6ff29f04d7ed7d5 Mon Sep 17 00:00:00 2001
From: Talbert <talbertc@usgs.gov>
Date: Mon, 20 Aug 2018 10:21:31 -0600
Subject: [PATCH] Bug fix for get_doi returning an error on valid DOIs

---
 usgs_datatools/doi.py | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)

diff --git a/usgs_datatools/doi.py b/usgs_datatools/doi.py
index 2d63557..3f91616 100644
--- a/usgs_datatools/doi.py
+++ b/usgs_datatools/doi.py
@@ -122,7 +122,8 @@ class DoiSession:
         response_status = self._session.get(
             self._base_doi_url + "doi/" + doi
         )
-        if response_status == 200:
+
+        if response_status.status_code == 200:
             return response_status.json()
         else:
             return {
@@ -141,6 +142,7 @@ class DoiSession:
         response_status = self._session.put(
             self._base_doi_url + "doi/" + doi["doi"], json=doi
         )
+
         if response_status.status_code == 200:
             return response_status.json()
         else:
-- 
2.18.0.windows.1

